---
abstract: 'Unity Dash from Web browsers (experimental)'
author:
  - 'Toshio Ito <toshioito@cpan.org>'
build_requires:
  Test::MockModule: 0.05
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Dash
no_index:
  directory:
    - eg
    - inc
    - t
    - xt
  file:
    - README.pod
provides:
  Web::Dash:
    file: lib/Web/Dash.pm
    version: 0.02
  Web::Dash::DeeModel:
    file: lib/Web/Dash/DeeModel.pm
    version: 0.02
  Web::Dash::Lens:
    file: lib/Web/Dash/Lens.pm
    version: 0.02
  Web::Dash::Util:
    file: lib/Web/Dash/Util.pm
    version: 0
requires:
  AnyEvent::DBus: 0.31
  Async::Queue: 0.02
  Carp: 0
  Encode: 0
  File::Find: 0
  Future::Q: 0.012
  Getopt::Long: 0
  Net::DBus: 1.0
  Plack: 0
  Plack::Request: 0
  Plack::Runner: 0
  Plack::Util: 0
  Pod::Usage: 0
  Scalar::Util: 1.20
  Try::Tiny: 0
  Twiggy: 0
  perl: 5.006
resources:
  repository: git://github.com/debug-ito/Web-Dash.git
version: 0.02
